name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install SERVER deps
        run: npm install

      - name: Install CLIENT deps
        run: npm install
        working-directory: ./bloglist-frontend
