name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install SERVER deps
        run: npm install

      - name: Install CLIENT deps
        run: npm install
        working-directory: ./bloglist-frontend

      - name: Lint SERVER
        run: npm run lint

      - name: Lint CLIENT
        run: npm run lint
        working-directory: ./bloglist-frontend
      # - name: Test SERVER
      #   run: npm test

      # - name: Test CLIENT

      - name: Build CLIENT
        run: npm run build
        working-directory: ./bloglist-frontend
